### ISSUE TITLE
`mapboxgl is not defined` on playground when using Firefox

### ISSUE THREAD

**Issue by Kalv1** [AlexLavoie42/Nuxt-Mapbox#13]
Is it possible to reup the playground ( 500 issue maxboxgl is not defined ) 

![image](https://user-images.githubusercontent.com/71704050/229810499-a2687acc-f636-4557-b10e-865fe26e738b.png)

**Comment by AlexLavoie42** [comment]
I can't seem to reproduce this issue. Running the playground works fine on my end. Mapboxgl comes from the CDN instead of NPM (because of #2), so perhaps it is some sort of network issue?

**Comment by Kalv1** [comment]
Ok this is weird... Maybe the CDN is not available in my geographical area ( Europe / France ). I tried on another ip and another pc and I have exactly the same problem, I can't get a playground that works.

I admit that it bothers me because I have a problem with the modules and I would have liked to see the playground working in order to possibly detect where my problem came from.

**Comment by AlexLavoie42** [comment]
Yup, can confirm that it does the same for me on Firefox. I think its safe to assume that the issue is caused by the stackblitz webcontainer on firefox. I will report the issue to stackblitz and see if we can get it resolved.

![image](https://user-images.githubusercontent.com/9439243/230146979-4e6d9c38-ec4f-497c-b748-d9e3bb674fd5.png)
