### ISSUE TITLE
TypeScript error in `/components/DefaultPopup.vue:18:69 `

### ISSUE THREAD

**Issue by steklopod** [AlexLavoie42/Nuxt-Mapbox#22]
Steps to reproduce:
```
pnpm add vue-tsc

pnpm run nuxi typecheck
```

<img width="1239" alt="Снимок экрана 2023-05-22 в 21 26 58" src="https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/29500153/47f42498-13e0-470f-b7de-76c78e293208">
<img width="874" alt="Снимок экрана 2023-05-22 в 21 33 15" src="https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/29500153/87884729-b92c-4c42-9537-38c49224f035">

<img width="1239" alt="Снимок экрана 2023-05-22 в 21 28 34" src="https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/29500153/b8e7da79-2dfd-48e6-bdfe-004ac4e6a510">

**Comment by AlexLavoie42** [comment]
For some reason typescript isn't realizing that `popup` can't be undefined here since we are calling `popup.on` first. This seems to work for me.
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/9439243/58674a59-c067-40c4-bf7f-b019186ff160)

Could you let me know which version of TS you are using? Perhaps this is an issue with `vue-tsc`? My assumption is that the `?.` syntax is what is breaking it.

For now I will wrap the whole thing in `if (popup)` which should hopefully fix the issue

**Comment by AlexLavoie42** [comment]
I'm not able to reproduce the first error you showed in a fresh install either. Would you be able to try and reproduce the issue [here?](https://stackblitz.com/edit/nuxt-starter-beudak)

![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/9439243/27e27c5a-3efa-4d63-837c-14f12d76785d)
