### ISSUE TITLE
how to use defineMapboxMarker

### ISSUE THREAD

**Issue by agracia-foticos** [AlexLavoie42/Nuxt-Mapbox#25]
Hello,

We have this reproduction link:

https://stackblitz.com/edit/nuxt-starter-zfc59i

How to use defineMapboxMarker???

In my environment throws 
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/77386602/55cdf5f1-2fa0-451b-8448-e5843cfbaa76)

**Comment by AlexLavoie42** [comment]
I believe the problem is you are passing a ref to the map itself. defineMapboxMarker is expecting the ref to contain custom html for the marker.

I recommend creating a new component for your marker and nesting it inside the map. This way the map id gets injected automatically. You could also just use the default marker if you don't want custom HTML. If you really want to use it without injecting the map id, you can also pass the map id manually as the last parameter to defineMapboxMarker after the callback.
