### ISSUE TITLE
adding dinamic defineMapboxMarker

### ISSUE THREAD

**Issue by agracia-foticos** [AlexLavoie42/Nuxt-Mapbox#27]
Its impossible to adding defineMapboxMarker with a array

Please i need help

I have this reproduction link
https://stackblitz.com/edit/nuxt-starter-eencva

We want to push markers into a map, but defineMapboxMarker not runs, not prints console.log, and dont push the markers...

How we can charge markers from array in a map with defineMapboxMarker??

**Comment by AlexLavoie42** [comment]
This is because you are passing a null ref to defineMapboxMarker. 
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/9439243/838783ce-1060-49f0-ab6f-9a8f94da1a52)

When the function recieves an html ref, it is always undefined at first, so we must wait until the HTML is loaded and the ref is no longer undefined. Since you are giving a ref that never becomes defined, we end up waiting indefinitely for HTML that does not exist.

For this to work, you should just pass null instead.
![image](https://github.com/AlexLavoie42/Nuxt-Mapbox/assets/9439243/72649320-1e25-467a-8008-353550259d09)

This seems a bit confusing, but this syntax is not really intended. The best way to use `defineMapboxMarker` is to create a new component for your marker, and nest it inside the map the same way as the default marker. This way you do not need to pass the map ID as it gets auto injected.

When you are not giving HTML to the marker, the syntax becomes MUCH simpler as you no longer need to use the callback:

```js
const marker = defineMapboxMarker(markerID, options)
marker?.setLngLat(lnglat)
```
